Repository Netflix4-0/Netflix4.0, pull requests merged in 2023-12, with the labels that each got.

#16 add movies.json
  src/data/movies.json
Labels: enhancement, good first issue

#39 Add missing posters
  src/data/movies.json
Labels: enhancement

#71 Bookmark movie in heroslide
  src/components/heroSlide/HeroSlide.css
  src/components/heroSlide/HeroSlide.tsx
  src/context/bookmarkContext.tsx
Labels: bug, enhancement

#75 Bookmark movie in movieview
  README.md
  src/routes/MovieView.css
  src/routes/MovieView.tsx
Labels: documentation, enhancement

#81 79 add recommended for you carousel in homepage
  README.md
  src/components/footer/Footer.css
  src/components/footer/Footer.tsx
  src/components/heroSlide/HeroSlide.tsx
  src/components/movies/Movies.tsx
  src/components/movies/movies.css
  src/components/thumbnail/Thumbnail.tsx
Labels: enhancement

#85 84 bookmarking bug on thumbnail
  src/components/thumbnail/Thumbnail.tsx
  src/context/bookmarkContext.tsx
  src/routes/Bookmarks.tsx
Labels: bug

#90 89 add additional tests to heroslide and movieview
  src/components/heroSlide/HeroSlide.tsx
  src/routes/Home.tsx
  src/routes/MovieView.tsx
  src/tests/HeroSlide.test.tsx
  src/tests/MovieView.test.tsx
  src/tests/setup.ts
Labels: testing

#98 Add test for homepage + styled search result + added bg-color for img…
  README.md
  src/components/footer/Footer.tsx
  src/components/header/Header.css
  src/components/movies/Movies.css
  src/components/movies/Movies.tsx
  src/components/thumbnail/Thumbnail.css
  src/index.css
  src/routes/CategoryPage.css
  src/routes/MovieView.css
  src/tests/App.test.tsx
  src/tests/Bookmarks.test.tsx
  src/tests/Homepage.test.tsx
Labels: enhancement, testing
